### ISSUE TITLE
Feature: Classroom Reservation

### ISSUE THREAD

**Issue by qwerzl** [Computerization/Enspire#484]
## Why?
1. For the CAS group in the student union, clubs constantly switch places and club leaders just send WeChat messages to the CAS group. This feature lets the club leaders to report this kind of action to one unified platform, and CAS group members can just visit the classrooms according to this platform.
2. For club leaders, we do have a classroom reservation spreadsheet shared by the CAS group. But who knows which classroom is where!

## What do we need
We should provide two views for the reservation panel. First one is a simple map like a fire evacuation map. You tap on the classroom then it pops up with information of it, whether it is used by another club on that day etc.. Second one is a spreadsheet-like list.

This feature should only be available for club leaders. Don't let them reserve if there's already a club occupying the classroom on that day. There should be two types of reservation, one is for long-term, one is just for that day.

**Comment by q1zhen** [comment]
# TODOs

- [ ] Providing a list of classrooms with their statuses
- [ ] Reserving & canceling the reservations
- [ ] Classroom occupation at fixed time periods
- [ ] Interactable floor plan of the whole campus

## and maybe

- [ ] Notification for status changes
- [ ] Exam week adjustments
- [ ] Search for a classroom by time period & requirements

**Comment by q1zhen** [comment]
I've done some sort of research and found that a DingTalk bot would be a very applicable way for notifications. It can be very easily deployed with the official APIs given.
