### ISSUE TITLE
Feature: New Members Recruitment

### ISSUE THREAD

**Issue by qwerzl** [Computerization/Enspire#485]
## Why?
1. Clubs always set up a WeChat group chat for recruitment. However as the 入群二维码 are public, there are always unwanted god-knows-who users not even from the school sending advertisements.
2. New 10th-graders don't really know the information about all the clubs. 

## What do we need?
Complete the "详细信息" in the club info page. When the button is clicked, we should navigate to a new page with infos about this club like club name, club introduction, past awards (we need to ask the CAS group for that) etc. And during club recruitment session, we need to show QR code of the clubs' WeChat groups. So there should also be an admin component for club leaders to update the QR code.

**Comment by at-wr** [comment]
## To-dos
- [x] Add "More information" Page
- [x] Includes Club name, Club description, Club member counts, Club supervisor
- [x] Introduce Safe HTML to Club Descriptions
- [x] Include Club Member List
- [x] Add Club Owners' Edit Mode
- [x] Add Recruitment QR Code Feature
- [ ] Feature "Past Awards" Block

### Extras

- [x] Search box in Club List

**Comment by qwerzl** [comment]
@at-wr It would be great to add a members list in "社团详情" page. The page layout should be like this (Forget the lines generated by GitHub):

# 世外信息化社
**Computerization**

## 简介
xxxx

## 成员
xxx (Alice), xxx (Banana)

## 奖项
- 2048年一星社团
- 2047年零星社团
- 2046年一星社团

**Comment by qwerzl** [comment]
Also, I forgot to add in the last review, you should add a `h-min` class to the "社团属性" card.

**Comment by at-wr** [comment]
> Also, I forgot to add in the last review, you should add a `h-min` class to the "社团属性" card.

OK, it will be added in the next PR
